### PR TITLE
Redirect user

### PR DESCRIPTION
**Pull request by Duncan-Frazer-imgtec**
OpenWrt for Ci40 notes are now a README.md and sit with the OpenWrt code in github.com\imgcreator\openwrt.

I've deleted the contents of this openwrt.md and replaced them with a redirect so that users hitting this original file will be lead to the new version which is being kept up to date

### CODE REVIEW

**Comment by abhijit-mahajani-imgtec** [comment]
Also we should add message that https://github.com/CreatorKit/creator-docs/tree/dev/creatorkit going to be moved at https://docs.imgcreator.io/creator

**Comment by nikhil-zinjurde-imgtec** [comment]
I think the message for pointing to https://docs.imgcreator.io/creator should really be added in the creator-docs/README.md, not here in OPENWRT.md, so the suggested change here is fine to make

**Comment by nikhil-zinjurde-imgtec** [comment]
Approved

**Comment by abhijit-mahajani-imgtec** [comment]
Approved

**Pull request merged**
